const path = require('path');
// const fs = require('fs');
// const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = require('../common/webpack.config')({

  entry: {},

  plugins: [

    new HtmlWebpackPlugin({
      cache: true,
      chunks: ['app'],
      favicon: path.join(__dirname, '../../favicon.ico'),
      filename: 'index.html',
      hash: true,
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      minify: false,
      template: path.join(__dirname, '../../index.html'),
      title: 'Demo',
    }),

  ],

  // load the CSS in a style tag in development
  cssLoaders: [
    { loader: 'style-loader' },
    { loader: 'css-loader',
      options: {
        importLoaders: true,
        localIdentName: '[path][local]',
        modules: true,
        sourceMap: true,
      },
    },
    { loader: 'postcss-loader' },
  ],

});
