version: '2'
services:
  #backend:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile-backend
  #    args:
  #      keyurl: ${BACKEND_KEYURL}
  #      branch: master
  #  ports:
  #    - "3000:3000"
  #  links:
  #    - dynamodb
  #s3server:
  #  ports:
  #    - "8001:8000"
  #  image: scality/s3server

  dynamodb:
    container_name: dynamodb
    ports:
      - "8000:8000"
    image: ryanratcliff/dynamodb

